Repository kubernetes/repo-infra, pull requests merged in 2019-09, with the labels that each got.

#122 Actually setup gopath properly in go_genrule
  .gitignore
  WORKSPACE
  defs/BUILD.bazel
  defs/go.bzl
  defs/testgen/BUILD.bazel
  defs/testgen/main.go
  defs/testpkg/BUILD.bazel
  defs/testpkg/pkg.go
  tools/BUILD.bazel
  tools/generate_crosstool/BUILD.bazel
  tools/generate_crosstool/main.go
  verify/BUILD.bazel
  verify/verify-crosstool.sh
Labels: approved, cncf-cla: yes, lgtm, size/XL

#125 Simplify travis script
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#126 Modernize OWNERS
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#128 Move travis logic into a bash script
  .travis.yml
  presubmit.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#127 Make Ben an approver
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#129 Create kazel, go, gofmt, targets
  BUILD.bazel
  cmd/kazel/BUILD.bazel
  cmd/kazel/README.rst
  cmd/kazel/config.go
  cmd/kazel/diff.go
  cmd/kazel/generator.go
  cmd/kazel/generator_test.go
  cmd/kazel/kazel.go
  cmd/kazel/kazel_test.go
  cmd/kazel/sourcerer.go
  verify/update-bazel.sh
  verify/verify-bazel.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#130 Create go.mod file
  go.mod
  go.sum
  presubmit.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#133 Update presubmit.sh to work on prow
  presubmit.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#131 Update run_in_workspace to work with external binaries
  defs/run_in_workspace.bzl
Labels: approved, cncf-cla: yes, lgtm, size/S

#132 Update rules_go
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/S

#134 Make travis do nothing
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#136 Delete travis
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#137 Delete Gopkg files
  Gopkg.lock
  Gopkg.toml
Labels: approved, cncf-cla: yes, lgtm, size/M

#140 Remove travis-specific test logic
  presubmit.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#139 Migrate gometalinter to golangci-lint
  .golangci.yml
  BUILD.bazel
  go.mod
  go.sum
  presubmit.sh
  verify/go-tools/verify-gometalinter.sh
  verify/go-tools/verify-govet.sh
  verify/tools.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#142 Remove redundant verify-govet.sh
  verify/go-tools/verify-govet.sh
Labels: approved, cncf-cla: yes, size/S

#135 Prepare for bazel rbe
  .bazelignore
  .bazelrc
  .bazelversion
Labels: approved, cncf-cla: yes, lgtm, size/M

#146 Enable RBE
  .bazelrc
  WORKSPACE
  presubmit.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#147 Update gazelle and buildifier to latest version
  go.mod
  go.sum
  repos.bzl
Labels: approved, cncf-cla: yes, lgtm, size/L

#148 Add Nico as a reviewer
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#150 Generate all-srcs targets in repo-infra
  .kazelcfg.json
  BUILD.bazel
  cmd/kazel/BUILD.bazel
  cmd/kazel/kazel.go
  defs/BUILD.bazel
  defs/testgen/BUILD.bazel
  defs/testpkg/BUILD.bazel
  tools/build_tar/BUILD.bazel
  verify/BUILD.bazel
  verify/boilerplate/BUILD.bazel
  verify/boilerplate/test/BUILD.bazel
  verify/update-bazel.sh
  verify/verify-bazel.sh
Labels: approved, cncf-cla: yes, lgtm, size/L, ¯\_(ツ)_/¯

#138 Print diffs when they exist
  verify/verify-bazel.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#151 Refactor verify-bazel
  .bazelrc
  BUILD.bazel
  hack/BUILD.bazel
  hack/update-bazel.sh
  hack/update-deps.sh
  hack/verify-bazel.sh
  hack/verify-deps.sh
  verify/verify-bazel.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#152 Migrate *-gofmt
  BUILD.bazel
  hack/BUILD.bazel
  hack/tools.go
  hack/update-gofmt.sh
  hack/verify-gofmt.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#155 Minor upgrade of all dependencies
  go.mod
  go.sum
  hack/tools.go
  repos.bzl
Labels: approved, cncf-cla: yes, lgtm, size/L

#153 Migrate golangci-lint check to //hack:verify-golangci-lint target
  hack/BUILD.bazel
  hack/verify-golangci-lint.sh
  verify/go-tools/verify-gometalinter.sh
Labels: approved, cncf-cla: yes, lgtm, size/M
