Repository kubernetes/repo-infra, pull requests merged in 2019-02, with the labels that each got.

#102 Add fejta to owners
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#103 bazel: update macros to support multi-arch and create a CROSSTOOL for gcc crossbuild-essential packages
  .travis.yml
  BUILD.bazel
  WORKSPACE
  defs/build.bzl
  defs/deb.bzl
  defs/rpm.bzl
  tools/BUILD.bazel
  tools/CROSSTOOL
  tools/generate_crosstool/BUILD.bazel
  tools/generate_crosstool/main.go
  verify/BUILD.bazel
  verify/verify-crosstool.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#104 Two tar fixes
  defs/pkg.bzl
  tools/build_tar/buildtar.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#105 Only save the hash in hash files (and add test)
  .travis.yml
  defs/BUILD.bazel
  defs/build.bzl
  defs/diff_test.sh
  defs/testdata/testfile.txt
  defs/testdata/testfile.txt.md5.expected
  defs/testdata/testfile.txt.sha1.expected
  defs/testdata/testfile.txt.sha512.expected
Labels: approved, cncf-cla: yes, size/M

#106 Fix Travis
  .bazelrc
  .travis.yml
  defs/diff_test.sh
Labels: approved, cncf-cla: yes, lgtm, size/S, ¯\_(ツ)_/¯
