Repository kubernetes/repo-infra, pull requests merged in 2019-01, with the labels that each got.

#93 Add SECURITY_CONTACTS file
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/S

#95 Use a correct Bazel workspace name for repo-infra
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, size/XS

#96 pkg_tar: update references to @io_k8s_repo_infra and add smoke test
  defs/BUILD.bazel
  defs/pkg.bzl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#99 support path conflict resolution in buildtar
  tools/build_tar/buildtar.go
Labels: approved, cncf-cla: yes, lgtm, size/M
