Repository kubernetes/repo-infra, pull requests merged in 2020-07, with the labels that each got.

#193 Remove nicoaragon from owners
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#194 Update rules_go to 0.22.7 to support go1.14.5 and go1.13.13
  load.bzl
Labels: approved, cncf-cla: yes, lgtm, priority/critical-urgent, size/S

#195 OWNERS: Add justaugustus
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#196 Update rules_go to 0.22.8 to support go1.14.6 and go1.13.14
  load.bzl
Labels: approved, cncf-cla: yes, lgtm, size/S

#198 Update dependencies
  go.mod
  go.sum
  repos.bzl
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#199 OWNERS: Add Verolop to reviewers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#200 OWNERS: Add approvers to reviewers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS

#201 deps: Update rules_go to v0.22.9
  load.bzl
Labels: approved, cncf-cla: yes, lgtm, priority/critical-urgent, sig/release, size/XS

#202 Support overriding go_sdk versions
  BUILD.bazel
  go/BUILD.bazel
  go/sdk_versions.bzl
  repos.bzl
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M

#203 go: Add go1.15rc1 SDK version
  go/sdk_versions.bzl
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M

#204 Add repo SECURITY.md
  SECURITY.md
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S
