Repository kubernetes/repo-infra, pull requests merged in 2020-04, with the labels that each got.

#183 feat(defs): add /usr/local/bin into PATH in go_genrule
  defs/go.bzl
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#184 dependencies/golangci-lint: update to use release v1.24.0
  go.mod
  go.sum
  repos.bzl
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#185 Switch to klog v2
  cmd/kazel/BUILD.bazel
  cmd/kazel/kazel.go
  go.mod
  go.sum
  repos.bzl
  tools/build_tar/BUILD.bazel
  tools/build_tar/buildtar.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#186 Update toolchains, rules_go, rules_nodejs.
  load.bzl
Labels: approved, cncf-cla: yes, lgtm, size/S

#187 Update golangci lint to v1.25.0
  go.mod
  go.sum
  repos.bzl
Labels: approved, cncf-cla: yes, lgtm, size/L
