Repository kubernetes/repo-infra, pull requests merged in 2020-03, with the labels that each got.

#178 Update repo-infra dependencies
  .bazelrc
  WORKSPACE
  defs/deb.bzl
  go.mod
  go.sum
  hack/BUILD.bazel
  load.bzl
  repos.bzl
Labels: approved, cncf-cla: yes, lgtm, size/L

#179 export goroot in go_genrule
  defs/go.bzl
Labels: approved, cncf-cla: yes, lgtm, size/XS

#180 bump repo-infra to bazel 2.2.0
  .bazelversion
  load.bzl
  repos.bzl
Labels: approved, cncf-cla: yes, lgtm, size/S
