Repository kubernetes/repo-infra, pull requests merged in 2020-11, with the labels that each got.

#212 Support go1.15.5
  load.bzl
  repos.bzl
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S

#214 Allow build as external repo with Bazel 3.7.0
  defs/go.bzl
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, sig/release, size/S

#213 Fix _go_genrule_impl in build env where src files cannot be moved
  defs/go.bzl
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS
