Repository kubernetes/repo-infra, pull requests merged in 2020-01, with the labels that each got.

#170 Update golangci-lint dependency to v1.22.2
  go.mod
  go.sum
  repos.bzl
Labels: approved, cncf-cla: yes, lgtm, size/L

#171 Update bazel dependencies
  .bazelversion
  load.bzl
Labels: approved, cncf-cla: yes, lgtm, size/S

#172 Update golangci-lint to v1.23.1
  go.mod
  go.sum
  repos.bzl
Labels: approved, cncf-cla: yes, lgtm, size/L

#174 Counterfeiter files are generated
  hack/verify_boilerplate.py
Labels: approved, cncf-cla: yes, lgtm, size/XS
