Repository kubernetes/repo-infra, pull requests merged in 2021-04, with the labels that each got.

#234 rules_go: update to use go1.15.11
  WORKSPACE
  go/sdk_versions.bzl
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M

#235 Set verify-golangci-lint timeout to 15m.
  BUILD.bazel
  hack/BUILD.bazel
  hack/update-bazel.sh
  third_party/io_bazel_rules_go/BUILD
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S

#238 WORKSPACE: Don't force go version in `configure()` directive
  WORKSPACE
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS
