Repository kubernetes/repo-infra, pull requests merged in 2021-01, with the labels that each got.

#217 bump repo-infra to bazel 3.4.1 and rules_go 0.25.1
  .bazelrc
  .bazelversion
  BUILD.bazel
  cmd/kazel/kazel.go
  defs/go.bzl
  defs/private/gcilint_repository.bzl
  go.mod
  go.sum
  hack/BUILD.bazel
  hack/tools.go
  load.bzl
  repos.bzl
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XXL

#218 Add an action to test build on macos
  .github/workflows/build-test.yml
  defs/private/gcilint_repository.bzl
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M

#220 cache bazelisk directory in build-test
  .github/workflows/build-test.yml
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/S

#219 fix duplicate dependency on golang.org/x/tools
  go.mod
  go.sum
  repos.bzl
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M

#221 carry patch to not override TMPDIR in go_test runner
  load.bzl
  third_party/io_bazel_rules_go/BUILD
  third_party/io_bazel_rules_go/dont-set-TEST_TMPDIR-to-TMPDIR-in-the-test-runner.patch
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/M

#223 Update bazel_toolchains to 3.7.2
  load.bzl
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS
