Repository kubernetes/repo-infra, pull requests merged in 2021-02, with the labels that each got.

#225 Don't use run_shell with list as cmd
  defs/go.bzl
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/release, size/S

#227 Update README.rst
  cmd/kazel/README.rst
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, sig/release, size/XS

#228 [v0.1.x] Support go1.15.8
  .bazelversion
  load.bzl
  repos.bzl
  third_party/io_bazel_rules_go/BUILD
  third_party/io_bazel_rules_go/dont-set-TEST_TMPDIR-to-TMPDIR-in-the-test-runner.patch
Labels: approved, cncf-cla: yes, lgtm, priority/critical-urgent, sig/release, size/M

#229 fix go_genrule for 1.16
  defs/go.bzl
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XS
